### ISSUE TITLE
ignore /root/.small-dragonfly/dfdaemon/data/: not a regular file

### ISSUE THREAD

**Issue by MCC-NO1** [dragonflyoss/Dragonfly#773] opened 2019-08-01 13:43 UTC
## Question

I use dfdaemon to pull image from supernode success in the first time. but, when I try again, the dfdaemon logs this error.
![image](https://user-images.githubusercontent.com/27477336/62298173-0fd91800-b4a5-11e9-9ed6-6abb67bffa25.png)

**Comment by yeya24** [comment] 2019-08-01 13:51
Thanks for this question.
This output is kind of confusing but it is not an error. It just means skip running gc in /data directory.
Maybe it is better to make this log to debug level.

**Comment by yeya24** [comment] 2019-08-03 06:47
@MCC-NO1  Since it is not a bug, I will close this issue. If you have any other questions about this, feel free to reopen it.

**Closed by yeya24** 2019-08-03 06:47 UTC
Labels: kind/question
